### ISSUE TITLE
Incluir atividade

### ISSUE THREAD

**Issue by tomasbarcellos** [luisapuppin/riscos#10]
Módulo de atividades (sua vinculação ao risco deve ser opcional)

- [x] Criar modelo no bd
- [x] Registrar no admin.py
- [x] Criar formulário
- [x] Criar urls
- [x] Criar view
- [x] Html para cadastrar
- [x] Html para detalhes

No Banco:
- [x] Incluir um campo anulável "id_atividade" na tabela de riscos

**Comment by tomasbarcellos** [comment]
- [ ] Incluir um campo anulável "id_atividade" na tabela de riscos

**Comment by tomasbarcellos** [comment]
Esta issue vai ficar parada até resolvermos as questões levantadas nas issues #28 e #29

**Comment by luisapuppin** [comment]
Novo módulo acrescentado pelo PR #32
