### ISSUE TITLE
Opções de cadastro de risco

### ISSUE THREAD

**Issue by tomasbarcellos** [luisapuppin/riscos#14]
A tela de criar riscos deve ter dois botões para cadastrar:

1. Criar risco e detalhar processo, e
2. Criar risco e criar novo risco no mesmo processo.

Os texto dos botões podem ser claramente melhorados.a

**Comment by luisapuppin** [comment]
Botões criados na página de cadastrar risco. Ainda necessita de retornar o formulário pré-preenchido.
Desenv https://github.com/luisapuppin/riscos/pull/18
