### ISSUE TITLE
Banco de dados perene no Docker

### ISSUE THREAD

**Issue by tomasbarcellos** [luisapuppin/riscos#24]
Hoje, toda vez que o docker é reiniciado, ele recria o banco de dados e perde as informações incluídas no último uso da aplicação.

Possíveis fontes para a solução:
1. [How do you perform Django database migrations when using Docker-Compose?
](https://stackoverflow.com/questions/33992867/how-do-you-perform-django-database-migrations-when-using-docker-compose)
2. [Auto-reloading of code changes with Django development in Docker with Gunicorn
](https://stackoverflow.com/questions/32022014/auto-reloading-of-code-changes-with-django-development-in-docker-with-gunicorn)
3. [Blog realpython](https://realpython.com/django-development-with-docker-compose-and-machine/)
4. [Dockerfile](https://github.com/interlegis/sapl/blob/3.1.x/Dockerfile) e [docker-compose.yml](https://github.com/interlegis/sapl/blob/3.1.x/docker-compose.yml) usados no projeto SAPL

**Comment by luisapuppin** [comment]
Bug corrigido pelo PR #25.
