### ISSUE TITLE
Alterações no template de criar

### ISSUE THREAD

**Issue by tomasbarcellos** [luisapuppin/riscos#29]
1. Em razão das mudanças propostas nas issues #8 e #28, poderemos remover os dropdowns e ajax dos templates de criar
2. Todas as telas de criar devem ter três opções para cadastrar:
    2.1. Cadastrar e detalhar
    2.2. Cadastrar e continuar cadastrando no mesmo item (processo, risco, etc)
    2.3. Cadastrar e ir para o próximo passo. Ex: Cadastrar um processo e começar a cadastrar riscos naquele processo.

**Comment by tomasbarcellos** [comment]
O item 2 está relacionado com a issue #7

**Comment by luisapuppin** [comment]
Proposta de template aceita pelo PR #30
