### ISSUE TITLE
Incluir tratamento

### ISSUE THREAD

**Issue by luisapuppin** [luisapuppin/riscos#4]
Módulo de controle dos riscos
- [x] Criar modelo no bd
- [x] Registrar no admin.py
- [x] Criar formulário
- [x] Criar formulário ajax (se necessário)
- [x] Criar view
- [x] Criar view ajax (se necessário)
- [x] Html para cadastrar
- [x] Html para detalhes
- [x] Html para ajax (se necessário)

**Comment by tomasbarcellos** [comment]
O tratamento deve incluir tanto i) controles quanto ii) planos de ação

**Comment by luisapuppin** [comment]
As tabelas de causa e consequência serão unidas e o tratamento será vinculado a tabela resultante da união, e não mais ao risco.

**Comment by luisapuppin** [comment]
Adicionei o ajax no modelo, porém teremos que revê-lo se formos parar de usar o ajax.

**Comment by luisapuppin** [comment]
Fechado em razão do PR #21
