### ISSUE TITLE
Separar consulta e lista de criação

### ISSUE THREAD

**Issue by luisapuppin** [luisapuppin/riscos#42]
Criar nova interface para indicar o nível superior do cadastramento de novos registros (listar_criar). A interface atual terá nova classificação de consulta.

O template de listar_criar deverá ter tabela que indique todos os níveis até o nível pai do que será cadastrado.

**Comment by tomasbarcellos** [comment]
- [ ] Alterar barra de navegação
- [ ] Criar template para lista de criação: processo
- [ ] Criar template para lista de criação: risco

**Comment by luisapuppin** [comment]
Issue fechada em razão da issue #52
