### ISSUE TITLE
Alterar template de detalhamento: planejamento e cadeia

### ISSUE THREAD

**Issue by luisapuppin** [luisapuppin/riscos#43]
Alterar template de detalhamento: planejamento, cadeia e tratamento de forma que estes entrem no padrão em vigência do template de detalhar.

**Comment by tomasbarcellos** [comment]
- [ ] Planejamento
- [ ] Cadeia

**Comment by luisapuppin** [comment]
Proposta de solução feita no PR #51

**Comment by luisapuppin** [comment]
Issue resolvida no PR #51
