### ISSUE TITLE
Listar tratamentos e plano de ação no template de detalhamento dos riscos

### ISSUE THREAD

**Issue by luisapuppin** [luisapuppin/riscos#44]
Alterar template de detalhamento de riscos para mostrar os tratamentos e planos de ação cadastrados no risco.

**Comment by tomasbarcellos** [comment]
As atividades devem ser apresentadas na sua ordem de ocorrência (campo do objeto Atividade).

- [ ] O texto das atividades deve ser: <ordem> -  <nome>

Exemplo:
> 1 - Identificar risco
> 2 - Avaliar risco
> 3 - Propor controles

**Comment by tomasbarcellos** [comment]
Resolvida no Pull Request #55
