### ISSUE TITLE
Criar módulo de monitoramento

### ISSUE THREAD

**Issue by tomasbarcellos** [luisapuppin/riscos#49]

**Comment by tomasbarcellos** [comment]
O módulo deve apresentar todos os tratamentos ao usuário para que possa atualizar:

1. Andamento do plano de ação e
2. Justificativa

**Comment by tomasbarcellos** [comment]
O módulo estará sempre disponível para o usuário ou apenas nos períodos em que o monitoramento deve ser realizado? :thinking:

**Comment by tomasbarcellos** [comment]
@luisapuppin, fiz uma proposta. Está no branch de desenv. Você pode dar uma olhada?

**Comment by luisapuppin** [comment]
Proposta aceita. #63
