### ISSUE TITLE
Repensar casos de delete

### ISSUE THREAD

**Issue by luisapuppin** [luisapuppin/riscos#6]
Hoje todos os deletes estão `on_delete=models.CASCADE`. Este caso não é desejável para todos os cenários. 

Exemplo: se um tipo de risco for deletado, não é interessante perder todos os riscos que estavam associados a ele.

**Comment by tomasbarcellos** [comment]
As opões são [essas](https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.ForeignKey.on_delete).

Me parece que temos três casos:
1. Objeto vinculado pela FK é superior, como um macroprocesso em relação a um processo. Neste caso deve ser usada `on_delete=models.CASCADE` para que todos os processos daquele macroprocesso sejam deletados.

2. Objeto vinculado pela FK é um apenas uma descrição dos códigos usados na tabela. É o caso do relacionamento entre impacto ou probabilidade e risco. Neste caso creio que deveria ser usada a opção  `on_delete=models.DO_NOTHING`. Uma probabilidade 3 será sempre menor que  probabilidade 5, independente da descrição utilizada.

3. Objeto vinculado pela FK não é superior, mas o id não guarda nenhuma relação com seu significado. Este é o caso entre tipo de risco e risco. Apenas por saber que o código do tipo é 1 ou 7 não sei nada sobre o tipo do risco. Neste caso creio que deveria ser usada a opção `on_delete=models.PROTECT` para que não percamos a informação inserida pelo usuário.

**Comment by luisapuppin** [comment]
Inicialmente todos os casos de delete foram passados para `on-delete=models.PROTECT` para proteção do sistema (desenv https://github.com/luisapuppin/riscos/pull/16).
