### ISSUE TITLE
Criar novos redirecionamentos para os formulários

### ISSUE THREAD

**Issue by luisapuppin** [luisapuppin/riscos#7]
Todo formulário terá as opções:
1. Cadastrar novo item;
2. Cadastrar e continuar o fluxo.

**Comment by tomasbarcellos** [comment]
Olhando a tela de atividade, não faz muito sentido ter os dois botões propostos nesta issue nessa tela. Isso porque os botões de `+` e `-` (formset) já cumprem o mesmo papel. Eu deixaria apenas o botão "criar atividade e detalhar processo".
O que acha, @luisapuppin ?

**Comment by luisapuppin** [comment]
@tomasbarcellos Sim, não há a necessidade de criar um botão para cadastrar novamente. Basta que você deixe o botão de "criar e detalhar".
