### ISSUE TITLE
Pensar no esquema de urls

### ISSUE THREAD

**Issue by luisapuppin** [luisapuppin/riscos#8]
Definir método consistente para todas as urls do sistema.

**Comment by tomasbarcellos** [comment]
Os exemplos abaixo devem descrever as seguintes situações:
1. Cadastrar um processo no macroprocesso de *id* 5
2. Cadastrar um risco no processo de *id* 24
3. Detalhar o risco cadastrado, cujo *id* é 73
4. Listar os riscos do processo 24

#### Proposta 1

`/{nivel}/{id_nivel_superior}/{ação}/{id_nivel}`

exemplos: 
> /processo/5/cadastrar
> /risco/24/cadastrar
> /risco/detalhar/73
> /risco/listar/24

#### Proposta 2
`/{ação}/{id_nivel_superior}/{nivel}/{id_nivel}`

exemplos:
> /cadastrar/5/processo
> /cadastrar/24/risco
> /detalhar/risco/73
> /listar/24/risco

#### Proposta 3
`/{ação}/{nivel}/{id_nivel}/{nivel_supeior}/{id_nivel_supeior}`

exemplos:
> /cadastrar/processo/macroprocesso/5
> /cadastrar/risco/processo/24
> /detalhar/risco/73
> /listar/risco/processo/24

#### Proposta 4
`/{ação}/{nivel_supeior}/{id_nivel_supeior}/{nivel}/{id_nivel}`

exemplos
> /cadastrar/macroprocesso/5/processo
> /cadastrar/processo/24/risco
> /detalhar/risco/73
> /listar/processo/24/risco

Em todos os casos os *id*s seriam opcionais dependendo da *url* a ser formada.

**Comment by tomasbarcellos** [comment]
O esquema de url escolhido foi:
`/{nivel}/[{id_nivel}]/{ação}/[{argumentos_ação}]`

Os pedaços entre `[]` denotam argumentos opcionais.

Neste esquema, os exemplos ficariam assim:

> /macroprocesso/5/criar/processo
> /processo/24/criar/risco
> /risco/73/detalhar/
> /risco/listar/?processo=24

A sintaxe do 4º exemplo não está fechada. Pode sofrer alterações.

**Comment by luisapuppin** [comment]
Issue fechada devido a decisão de seguir o modelo descrito acima. A issue será reaberta se o modelo tiver que ser alterado.
